name: Linting

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - stable

jobs:
  lint:
    runs-on: 'windows-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Python packages
        run: |
          python -m pip install --upgrade -r requirements-setuptools.txt
          python -m pip install -r requirements-lint.txt

      - name: Test if requirements files are up to date
        shell: bash
        run: |
          set -e
          python tools/update_requirements.py --quiet
          git diff --exit-code

  mypy-required:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade -r requirements-setuptools.txt
          python -m pip install -r requirements.txt -e ".[gui,exporters,server,test,typing]"

      - name: build ui files
        run: python setup.py build_ui

      - name: mypy
        uses: liskin/gh-problem-matcher-wrap@v3
        with:
          linters: mypy
          run: mypy

  mypy-modified:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade -r requirements-setuptools.txt
          python -m pip install -r requirements.txt -e ".[gui,exporters,server,test,typing]"

      - name: build ui files
        run: python setup.py build_ui

      - name: Mypy on modified files
        uses: tsuyoshicho/action-mypy@v5
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-check
          setup_method: nothing
          level: warning
          fail_on_error: false
          install_types: false
